version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.12
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-54-220-35-19.eu-west-1.compute.amazonaws.com
            port: '5432'
            database: d2v2ob1umpmdj1
            ssl: true
            user: idrqgvyuyqmdgd
            password: b2de327563db4ec8f23a208a819e7b4709afd792dcd88def61604e4bda8332ea
            migrations: true